import { BookOpen, ChevronDown, FileText, Menu, Scale, X } from 'lucide-react'
import { useState } from 'react'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '../../@/components/ui/dropdown-menu'

const resources = [['Blog', '/resources/blog'], ['Changelog', '/resources/changelog'], ['FAQ', '/resources/faq'], ['About', '/resources/about'], ['Contact', '/resources/contact']]
const legal = [['Terms', '/legal/terms'], ['Privacy', '/legal/privacy'], ['Cookie policy', '/legal/cookies'], ['Data processing', '/legal/dpa'], ['Acceptable use', '/legal/acceptable-use'], ['Subprocessors', '/legal/subprocessors'], ['Security', '/legal/security']]

function StackMenu({ label, icon: Icon, items }: { label: string; icon: typeof BookOpen; items: string[][] }) {
  return <DropdownMenu><DropdownMenuTrigger className="site-nav-trigger">{label}<ChevronDown className="size-3.5" /></DropdownMenuTrigger><DropdownMenuContent align="start" className="site-nav-menu"><DropdownMenuLabel className="site-nav-label"><Icon className="size-3.5" />{label}</DropdownMenuLabel><DropdownMenuSeparator className="bg-[#e7e7e1]" />{items.map(([name, href]) => <DropdownMenuItem key={name} asChild><a href={href} className="site-nav-menu-item">{name}</a></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>
}

export function SiteNav({ signedIn = false, active }: { signedIn?: boolean; active?: 'product' | 'pricing' | 'resources' | 'docs' }) {
  const [open, setOpen] = useState(false)
  const marketingOnly = import.meta.env.VITE_MARKETING_ONLY === 'true'
  const workspaceHref = marketingOnly ? '/resources/contact' : signedIn ? '/dashboard' : '/auth/signup'
  const cta = marketingOnly ? 'Request access' : signedIn ? 'Open dashboard' : 'Start building'
  return <header className="relative z-50 mx-auto max-w-7xl px-5 sm:px-8"><nav className="flex h-20 items-center justify-between border-b border-[#e7e7e1]"><a href="/" className="flex items-center gap-2.5 text-[15px] font-semibold tracking-[-0.02em]"><span className="grid size-7 place-items-center rounded-md bg-[#292a24] text-xs text-[#dedb49]">S</span>Sulphur</a><div className="hidden items-center gap-1 lg:flex"><a className={`site-nav-link ${active === 'product' ? 'active' : ''}`} href="/product">Product</a><a className="site-nav-link" href="/why-sulphur">Why Sulphur</a><a className={`site-nav-link ${active === 'pricing' ? 'active' : ''}`} href="/pricing">Pricing</a><a className={`site-nav-link ${active === 'docs' ? 'active' : ''}`} href="/docs">Docs</a><StackMenu label="Resources" icon={BookOpen} items={resources} /><StackMenu label="Legal" icon={Scale} items={legal} /></div><div className="hidden lg:block"><a href={workspaceHref} className="site-nav-cta">{cta}</a></div><button onClick={() => setOpen(!open)} className="grid size-9 place-items-center rounded-lg border border-[#deded7] bg-white lg:hidden" aria-label="Toggle navigation">{open ? <X className="size-4" /> : <Menu className="size-4" />}</button></nav>{open && <div className="site-nav-mobile-menu absolute left-5 right-5 top-[70px] rounded-xl border border-[#deded7] bg-white p-3 shadow-xl lg:hidden"><a className="site-nav-mobile" href="/product">Product</a><a className="site-nav-mobile" href="/why-sulphur">Why Sulphur</a><a className="site-nav-mobile" href="/pricing">Pricing</a><a className="site-nav-mobile" href="/docs">Docs</a><p className="site-nav-mobile-label">Resources</p>{resources.map(([name, href]) => <a className="site-nav-mobile sub" key={name} href={href}>{name}</a>)}<p className="site-nav-mobile-label">Legal</p>{legal.map(([name, href]) => <a className="site-nav-mobile sub" key={name} href={href}>{name}</a>)}<a href={workspaceHref} className="mt-2 flex items-center justify-center rounded-md bg-[#292a24] px-3 py-2.5 text-sm font-semibold text-white">{cta}</a></div>}</header>
}
