import { useEffect, useMemo, useState } from "react";
import { Activity, AppWindow, ArrowUpRight, BadgeDollarSign, BarChart3, ChevronDown, CircleDollarSign, Clock3, Copy, LayoutDashboard, LayoutGrid, Mail, Pause, Play, Plus, RefreshCw, Search, ShieldCheck, Tag, Users } from "lucide-react";
import { Badge, Button, Card, Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger, Input, Label } from "./components/ui";

type AdminData = {
  metrics: { users: number; trials: number; activeSessions: number; apps: number; revenueCents: number };
  users: Array<{ id: string; name: string; email: string; createdAt: string; appCount: number; sessionCount: number; plan: string | null; billing_status: string | null; trialEndsAt: string | null }>;
  apps: Array<{ id: string; display_name: string; size: number; status: string; createdAt: string; owner: string; email: string }>;
  sessions: Array<{ id: string; status: string; createdAt: string; endedAt: string | null; app: string; owner: string; email: string }>;
  promos: Array<{ id: string; code: string; discount_percent: number; active: boolean; max_redemptions: number | null; expiresAt: string | null; redemptions: number }>;
  payments: Array<{ id: string; amount_cents: number; currency: string; status: string; provider: string; createdAt: string; owner: string; email: string }>;
  activity: Array<{ day: string; signups: number; sessions: number; mcpCalls: number }>;
};

const apiBase = import.meta.env.VITE_AUTH_URL ?? window.location.origin;
async function adminRequest<T>(path: string, init?: RequestInit) {
  const response = await fetch(`${apiBase}${path}`, { ...init, credentials: "include", headers: { "Content-Type": "application/json", ...init?.headers } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.message ?? "The admin request could not be completed.");
  return body as T;
}
const date = (value: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const money = (cents: number, currency = "USD") => new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 0 }).format(cents / 100);
const bytes = (value: number) => value < 1024 * 1024 ? `${Math.ceil(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`;
const tone = (value: string | null) => ["active", "paid", "ready", "running"].includes(value ?? "") ? "safe" : ["paused", "failed", "past_due"].includes(value ?? "") ? "warning" : "neutral" as const;

function DataTable({ title, description, children, action, footer }: { title: string; description: string; children: React.ReactNode; action?: React.ReactNode; footer?: React.ReactNode }) {
  return <Card className="admin-table-card"><div className="admin-table-heading"><div><h2>{title}</h2><p>{description}</p></div>{action}</div><div className="admin-table-wrap">{children}</div>{footer}</Card>;
}

function Pagination({ total, page, onPageChange }: { total: number; page: number; onPageChange(page: number): void }) {
  const pageSize = 10, pages = Math.max(1, Math.ceil(total / pageSize));
  if (total <= pageSize) return null;
  return <div className="admin-pagination"><span>Showing {(page - 1) * pageSize + 1}–{Math.min(page * pageSize, total)} of {total}</span><div><button disabled={page === 1} onClick={() => onPageChange(page - 1)}>Previous</button><strong>{page} / {pages}</strong><button disabled={page === pages} onClick={() => onPageChange(page + 1)}>Next</button></div></div>;
}

const pageItems = <T,>(items: T[], page: number) => items.slice((page - 1) * 10, page * 10);

function NewPromo({ onCreated }: { onCreated(): void }) {
  const [open, setOpen] = useState(false), [code, setCode] = useState(""), [discount, setDiscount] = useState("20"), [limit, setLimit] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); setError(""); try { await adminRequest("/api/admin/promos", { method: "POST", body: JSON.stringify({ code, discountPercent: Number(discount), maxRedemptions: limit || undefined }) }); setOpen(false); setCode(""); setLimit(""); onCreated(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Promo could not be created."); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus size={15} /> New promo</Button></DialogTrigger><DialogContent><DialogTitle className="dialog-title">Create promo code</DialogTitle><DialogDescription className="dialog-description">Codes apply during checkout; payment processing remains provider-owned.</DialogDescription><div className="form-stack"><div><Label htmlFor="promo-code">Code</Label><Input id="promo-code" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="LAUNCH20" /></div><div><Label htmlFor="promo-discount">Percent off</Label><Input id="promo-discount" type="number" min="1" max="100" value={discount} onChange={(event) => setDiscount(event.target.value)} /></div><div><Label htmlFor="promo-limit">Redemption limit <span className="optional-label">Optional</span></Label><Input id="promo-limit" type="number" min="1" value={limit} onChange={(event) => setLimit(event.target.value)} /></div>{error && <p className="form-error">{error}</p>}<Button onClick={save} disabled={saving}>{saving ? "Creating…" : "Create promo"}</Button></div></DialogContent></Dialog>;
}

function AdminLogin({ onAuthenticated }: { onAuthenticated(): void }) {
  const [email, setEmail] = useState(""), [password, setPassword] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { await adminRequest("/api/admin/session", { method: "POST", body: JSON.stringify({ email, password }) }); onAuthenticated(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not authenticate."); } finally { setSaving(false); } };
  return <main className="admin-page admin-login"><form className="admin-login-card" onSubmit={submit}><div className="admin-login-mark"><ShieldCheck size={20}/></div><p className="eyebrow">SULPHUR OPERATIONS</p><h1>Administrator sign in</h1><p>Use the dedicated administrator credentials configured on the server.</p><div><Label htmlFor="admin-mail">Administrator email</Label><Input id="admin-mail" type="email" autoComplete="username" value={email} onChange={(event) => setEmail(event.target.value)} required /></div><div><Label htmlFor="admin-pass">Administrator password</Label><Input id="admin-pass" type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></div>{error && <p className="form-error" role="alert">{error}</p>}<Button disabled={saving}>{saving ? "Signing in…" : "Sign in to admin"}</Button></form></main>;
}

function BroadcastEmail({ onSent }: { onSent(result: { recipients: number; sent: number; suppressed: number; failed: number }): void }) {
  const [open, setOpen] = useState(false), [subject, setSubject] = useState(""), [message, setMessage] = useState(""), [category, setCategory] = useState<"announcement" | "product">("announcement"), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const send = async () => { setSaving(true); setError(""); try { const result = await adminRequest<{ recipients: number; sent: number; suppressed: number; failed: number }>("/api/admin/email/broadcast", { method: "POST", body: JSON.stringify({ subject, message, category }) }); setOpen(false); setSubject(""); setMessage(""); onSent(result); } catch (reason) { setError(reason instanceof Error ? reason.message : "Broadcast could not be sent."); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Mail size={15}/> Send email</Button></DialogTrigger><DialogContent><DialogTitle className="dialog-title">Email verified users</DialogTitle><DialogDescription className="dialog-description">Recipients who turned off this category are automatically excluded. Authentication messages cannot be sent from here.</DialogDescription><div className="form-stack"><div><Label htmlFor="email-category">Category</Label><select id="email-category" value={category} onChange={(event) => setCategory(event.target.value as "announcement" | "product")}><option value="announcement">Announcement</option><option value="product">Product update</option></select></div><div><Label htmlFor="broadcast-subject">Subject</Label><Input id="broadcast-subject" value={subject} maxLength={160} onChange={(event) => setSubject(event.target.value)} /></div><div><Label htmlFor="broadcast-message">Message</Label><textarea id="broadcast-message" value={message} maxLength={10000} rows={7} onChange={(event) => setMessage(event.target.value)} /></div>{error && <p className="form-error">{error}</p>}<Button onClick={() => void send()} disabled={saving || !subject.trim() || !message.trim()}>{saving ? "Sending…" : "Send to eligible users"}</Button></div></DialogContent></Dialog>;
}

export function AdminPage() {
  const [data, setData] = useState<AdminData | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [authenticated, setAuthenticated] = useState<boolean | null>(null), [query, setQuery] = useState(""), [section, setSection] = useState("overview"), [page, setPage] = useState(1), [notice, setNotice] = useState("");
  const load = async () => { setLoading(true); setError(""); try { setData(await adminRequest<AdminData>("/api/admin/overview")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Admin data could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { void (async () => { try { const session = await adminRequest<{ authenticated: boolean }>("/api/admin/session"); setAuthenticated(session.authenticated); if (session.authenticated) await load(); else setLoading(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "Admin authentication could not be checked."); setLoading(false); } })(); }, []);
  const users = useMemo(() => data?.users.filter((user) => `${user.name} ${user.email}`.toLowerCase().includes(query.toLowerCase())) ?? [], [data, query]);
  useEffect(() => setPage(1), [section, query]);
  const userAction = async (id: string, action: "pause" | "restore" | "extend_trial") => { try { await adminRequest(`/api/admin/users/${id}/access`, { method: "POST", body: JSON.stringify({ action }) }); setNotice(action === "extend_trial" ? "Trial extended by 14 days." : action === "pause" ? "Access paused." : "Access restored."); await load(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Action failed."); } };
  const togglePromo = async (id: string) => { try { await adminRequest(`/api/admin/promos/${id}/toggle`, { method: "POST" }); await load(); } catch (reason) { setNotice(reason instanceof Error ? reason.message : "Promo could not be updated."); } };
  if (authenticated === null || loading) return <main className="admin-page admin-loading">Loading administration…</main>;
  if (!authenticated) return <AdminLogin onAuthenticated={() => { setAuthenticated(true); void load(); }} />;
  if (error || !data) return <main className="admin-page admin-denied"><ShieldCheck size={24}/><h1>Admin workspace unavailable</h1><p>{error || "No admin data is available."}</p><p className="admin-muted">Configure <code>ADMIN_MAIL</code> and <code>ADMIN_PASS</code> on the server, then sign in again.</p></main>;
  const tabs = [["overview", BarChart3, "Overview"], ["users", Users, "Users"], ["apps", LayoutGrid, "Apps"], ["sessions", AppWindow, "Sessions"], ["promos", Tag, "Promo codes"], ["payments", CircleDollarSign, "Payments"], ["email", Mail, "Email"]] as const;
  return <main className="admin-page"><aside className="admin-sidebar"><a className="admin-sidebar-brand" href="/"><span className="brand-mark">S</span><span>Sulphur <small>Admin</small></span></a><div className="admin-sidebar-label">Operations</div><nav className="admin-nav">{tabs.map(([id, Icon, label]) => <button className={section === id ? "active" : ""} key={id} onClick={() => { setSection(id); setPage(1); }}><Icon size={16}/>{label}</button>)}</nav><div className="admin-nav-note"><ShieldCheck size={15}/><span>Every privileged action is recorded in the audit trail.</span></div><div className="admin-sidebar-bottom"><div className="admin-sidebar-label">Workspace</div><a href="/dashboard"><LayoutDashboard size={16}/> Product dashboard <ArrowUpRight size={13}/></a><a href="/"><ArrowUpRight size={16}/> Public site</a></div></aside><div className="admin-workspace"><header className="admin-header"><div><p className="eyebrow">SULPHUR OPERATIONS</p><h1>Admin command center</h1><p>Workspace records, trial conversion, operational activity, and commercial state.</p></div><div className="admin-header-actions"><Button variant="outline" onClick={() => void load()}><RefreshCw size={15}/> Refresh</Button></div></header>
    <div className="admin-metrics"><Card><Users/><span>Total users</span><strong>{data.metrics.users.toLocaleString()}</strong></Card><Card><Clock3/><span>Live trials</span><strong>{data.metrics.trials.toLocaleString()}</strong><small>14-day access windows</small></Card><Card><Activity/><span>Active sessions</span><strong>{data.metrics.activeSessions.toLocaleString()}</strong></Card><Card><BadgeDollarSign/><span>Paid revenue</span><strong>{money(data.metrics.revenueCents)}</strong><small>Captured transactions</small></Card></div>
    <div className="admin-layout"><section className="admin-content">{notice && <p className="admin-notice">{notice}</p>}
        {section === "overview" && <><Card className="admin-chart-card"><div className="admin-table-heading"><div><h2>14-day operating signal</h2><p>Account growth, sessions started, and MCP calls.</p></div><Badge tone="safe">Live data</Badge></div><div className="admin-chart">{data.activity.map((point) => { const maximum = Math.max(1, ...data.activity.flatMap((item) => [item.signups, item.sessions, item.mcpCalls])); return <div key={point.day} className="admin-bar-group" title={`${point.day}: ${point.signups} signups, ${point.sessions} sessions, ${point.mcpCalls} MCP calls`}><div className="admin-bars"><i style={{ height: `${Math.max(4, point.signups / maximum * 100)}%` }} /><i style={{ height: `${Math.max(4, point.sessions / maximum * 100)}%` }} /><i style={{ height: `${Math.max(4, point.mcpCalls / maximum * 100)}%` }} /></div><span>{point.day.slice(5)}</span></div>; })}</div><div className="admin-legend"><span><i/> Signups</span><span><i/> Sessions</span><span><i/> MCP calls</span></div></Card><DataTable title="Recent users" description="Newest 8 workspace accounts."><table><thead><tr><th>User</th><th>Plan</th><th>Trial ends</th><th>Apps</th><th>Sessions</th></tr></thead><tbody>{data.users.slice(0, 8).map((user) => <tr key={user.id}><td><strong>{user.name}</strong><small>{user.email}</small></td><td><Badge tone={tone(user.billing_status)}>{user.billing_status ?? "unassigned"}</Badge></td><td>{date(user.trialEndsAt)}</td><td>{user.appCount}</td><td>{user.sessionCount}</td></tr>)}</tbody></table></DataTable></>}
        {section === "users" && <DataTable title="Users" description="All signed-in workspace owners with their product and trial state." action={<div className="admin-search"><Search size={15}/><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search users" /></div>} footer={<Pagination total={users.length} page={page} onPageChange={setPage} />}><table><thead><tr><th>User</th><th>Created</th><th>Plan / status</th><th>Trial ends</th><th>Usage</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{pageItems(users, page).map((user) => <tr key={user.id}><td><strong>{user.name}</strong><small>{user.email}</small></td><td>{date(user.createdAt)}</td><td><strong className="admin-plan">{user.plan ?? "free"}</strong><Badge tone={tone(user.billing_status)}>{user.billing_status ?? "unassigned"}</Badge></td><td>{date(user.trialEndsAt)}</td><td>{user.appCount} apps · {user.sessionCount} sessions</td><td><div className="admin-row-actions"><button onClick={() => void userAction(user.id, "extend_trial")}>+14d</button>{user.billing_status === "paused" ? <button onClick={() => void userAction(user.id, "restore")}><Play size={13}/> Restore</button> : <button className="danger" onClick={() => void userAction(user.id, "pause")}><Pause size={13}/> Pause</button>}</div></td></tr>)}</tbody></table></DataTable>}
        {section === "apps" && <DataTable title="Uploaded apps" description="APK inventory across every workspace." footer={<Pagination total={data.apps.length} page={page} onPageChange={setPage} />}><table><thead><tr><th>App</th><th>Owner</th><th>Size</th><th>Status</th><th>Uploaded</th></tr></thead><tbody>{pageItems(data.apps, page).map((app) => <tr key={app.id}><td><strong>{app.display_name}</strong><small>{app.id}</small></td><td>{app.owner}<small>{app.email}</small></td><td>{bytes(app.size)}</td><td><Badge tone={tone(app.status)}>{app.status}</Badge></td><td>{date(app.createdAt)}</td></tr>)}</tbody></table></DataTable>}
        {section === "sessions" && <DataTable title="Android sessions" description="Live and historical environment records across workspaces." footer={<Pagination total={data.sessions.length} page={page} onPageChange={setPage} />}><table><thead><tr><th>App</th><th>Owner</th><th>Status</th><th>Started</th><th>Ended</th></tr></thead><tbody>{pageItems(data.sessions, page).map((session) => <tr key={session.id}><td><strong>{session.app}</strong><small>{session.id}</small></td><td>{session.owner}<small>{session.email}</small></td><td><Badge tone={tone(session.status)}>{session.status}</Badge></td><td>{date(session.createdAt)}</td><td>{date(session.endedAt)}</td></tr>)}</tbody></table></DataTable>}
        {section === "promos" && <DataTable title="Promo codes" description="Codes are activated here and applied at provider-backed checkout." action={<NewPromo onCreated={() => void load()}/>} footer={<Pagination total={data.promos.length} page={page} onPageChange={setPage} />}><table><thead><tr><th>Code</th><th>Discount</th><th>Redemptions</th><th>Expires</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{pageItems(data.promos, page).map((promo) => <tr key={promo.id}><td><strong>{promo.code}</strong></td><td>{promo.discount_percent}%</td><td>{promo.redemptions}{promo.max_redemptions ? ` / ${promo.max_redemptions}` : ""}</td><td>{date(promo.expiresAt)}</td><td><Badge tone={promo.active ? "safe" : "neutral"}>{promo.active ? "active" : "disabled"}</Badge></td><td><button className="admin-text-action" onClick={() => void togglePromo(promo.id)}>{promo.active ? "Disable" : "Enable"}</button></td></tr>)}</tbody></table></DataTable>}
        {section === "payments" && <DataTable title="Payments" description="Provider transaction state only—payment instruments never enter Sulphur." footer={<Pagination total={data.payments.length} page={page} onPageChange={setPage} />}><table><thead><tr><th>Customer</th><th>Amount</th><th>Provider</th><th>Status</th><th>Created</th></tr></thead><tbody>{pageItems(data.payments, page).map((payment) => <tr key={payment.id}><td><strong>{payment.owner}</strong><small>{payment.email}</small></td><td>{money(payment.amount_cents, payment.currency)}</td><td>{payment.provider}</td><td><Badge tone={tone(payment.status)}>{payment.status}</Badge></td><td>{date(payment.createdAt)}</td></tr>)}{!data.payments.length && <tr><td colSpan={5} className="admin-empty">No payment transactions have been imported from a provider.</td></tr>}</tbody></table></DataTable>}
        {section === "email" && <DataTable title="Customer email" description="Send a plain-text announcement or product update to every verified user who has opted in." action={<BroadcastEmail onSent={(result) => setNotice(`Email complete: ${result.sent} sent, ${result.suppressed} opted out, ${result.failed} failed.`)} />}><div className="admin-empty"><Mail size={20}/><p>Delivery history is recorded for every message. Optional categories respect each user’s email controls.</p></div></DataTable>}
      </section></div></div></main>;
}
