import {
  ArrowRight, Check, CheckCircle2, CircleCheck, Fingerprint, GitBranch,
  Globe2, Layers3, LockKeyhole, Menu, MonitorSmartphone, PanelTop, Play, ShieldCheck,
  Sparkles, Terminal, X,
} from 'lucide-react'
import { useState } from 'react'
import { Button } from './components/ui'
import { SessionDemoScreen, SessionPanel } from './components/session-panel'
import { BenchmarkStats } from './components/benchmark-stats'
import { SiteNav } from './components/site-nav'

const navLinks = [
  { name: 'Product', href: '/product' }, { name: 'How it works', href: '#how-it-works' },
  { name: 'Security', href: '#security' }, { name: 'Pricing', href: '#pricing' },
]

const features = [
  [MonitorSmartphone, 'An Android environment on demand', 'Turn an APK into a clean, observable Android session without managing devices or emulators.'],
  [Terminal, 'An agent that works within guardrails', 'Connect through MCP with snapshot-bound actions, clear policies, and approvals where they matter.'],
  [ShieldCheck, 'Control that scales with your team', 'Keep every session, connection, and action visible to the people responsible for your software.'],
] as const

const securityItems = [
  ['Tenant-isolated sessions', 'Every workspace gets a clean, dedicated Android environment.'],
  ['Egress blocked by default', 'Your APK cannot reach the public internet unless your policy explicitly allows it.'],
  ['Snapshot-bound actions', 'Agents act against fresh UI state—not stale coordinates or assumptions.'],
  ['Complete audit trail', 'See the human, connection, tool call, result, and policy decision behind every action.'],
]

function DashboardOverview(_: { appsCount: number }) {
  return <><div className="landing-hero-benchmark"><BenchmarkStats compact /></div><SessionPanel sessionId="demo-session-8f29" screen={<SessionDemoScreen />} setupAction={<Button>Set up MCP</Button>} demo /></>
}

export function LandingPage({ signedIn = false }: { signedIn?: boolean }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const workspaceHref = signedIn ? '/dashboard' : '/auth/signup'
  const dashboardHref = signedIn ? '/dashboard' : '/auth/login'
  return <main className="min-h-screen overflow-hidden bg-[#f8f8f6] text-[#292a24] selection:bg-[#d9ce22] selection:text-[#292a24]">
    <SiteNav signedIn={signedIn} />

    <section className="relative mx-auto max-w-7xl px-5 pb-20 pt-16 sm:px-8 sm:pb-28 sm:pt-24"><div className="landing-glow pointer-events-none absolute left-1/2 top-0 -z-0 h-[520px] w-[760px] -translate-x-1/2" /><div className="relative z-10 mx-auto max-w-4xl text-center"><p className="inline-flex items-center gap-2 rounded-full border border-[#e1e1d9] bg-white/80 px-3 py-1.5 text-[10px] font-semibold tracking-[0.11em] text-[#65665e] shadow-sm"><Sparkles className="size-3 text-[#77781d]" /> AGENT-READY ANDROID TESTING</p><h1 className="mt-7 text-balance text-[42px] font-semibold leading-[0.98] tracking-[-0.06em] text-[#292a24] sm:text-6xl lg:text-[76px]">The control plane for <span className="text-[#71721c]">mobile agents.</span></h1><p className="mx-auto mt-7 max-w-2xl text-pretty text-base leading-7 text-[#6d6e66] sm:text-lg">Give your AI agents a safe, observable Android environment—without handing over your devices, your network, or your peace of mind.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><a href={workspaceHref} className="inline-flex h-12 items-center gap-2 rounded-lg bg-[#292a24] px-5 text-sm font-semibold text-white shadow-[0_10px_22px_-10px_rgba(41,42,36,.7)] transition hover:-translate-y-0.5 hover:bg-[#41423b]">{signedIn ? 'Open your dashboard' : 'Create your workspace'} <ArrowRight className="size-4" /></a><a href="#product" className="inline-flex h-12 items-center gap-2 rounded-lg border border-[#d8d9d1] bg-white px-5 text-sm font-semibold text-[#41423a] transition hover:bg-[#f1f1eb]"><Play className="size-3.5 fill-current" /> See how it works</a></div><p className="mt-4 flex items-center justify-center gap-1.5 text-xs text-[#7a7b73]"><Check className="size-3.5 text-[#638157]" /> No credit card required <span className="mx-1 text-[#d3d4cc]">•</span> Private workspace from day one</p></div><div id="product" className="landing-dashboard-demo relative z-10 mx-auto mt-14 max-w-5xl overflow-hidden rounded-[22px] border border-[#d9dad2] bg-[#f8f8f6] shadow-[0_26px_80px_-34px_rgba(34,35,28,0.42)]"><DashboardOverview appsCount={1} /></div><div className="relative z-10 mx-auto mt-8 flex flex-wrap items-center justify-center gap-x-7 gap-y-3 text-[11px] font-medium tracking-[0.1em] text-[#919189]"><span className="flex items-center gap-2"><LockKeyhole className="size-3.5" /> EGRESS BLOCKED</span><span className="flex items-center gap-2"><CircleCheck className="size-3.5" /> AUDITABLE</span><span className="flex items-center gap-2"><Layers3 className="size-3.5" /> TENANT-ISOLATED</span></div></section>

    <section className="border-y border-[#e3e3dc] bg-[#efefe9] px-5 py-10 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-center text-[11px] font-semibold tracking-[0.12em] text-[#777870]">BUILT FOR THE WAY MODERN SOFTWARE TEAMS WORK</p><div className="mt-7 grid grid-cols-2 gap-5 text-center text-lg font-semibold tracking-[-0.04em] text-[#6b6c65] sm:grid-cols-4 sm:text-xl"><span>Mobile QA</span><span>Product teams</span><span>AI engineers</span><span>Security teams</span></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="max-w-2xl"><p className="landing-kicker">ONE SYSTEM. CLEAR BOUNDARIES.</p><h2 className="mt-4 text-balance text-3xl font-semibold tracking-[-0.05em] sm:text-5xl">Move quickly without making mobile automation a blind spot.</h2><p className="mt-5 max-w-xl text-base leading-7 text-[#6d6e66]">Sulphur gives agents the context they need to test Android apps and gives your team the controls it needs to stay accountable.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{features.map(([Icon, title, description]) => <article key={title} className="rounded-2xl border border-[#e1e1da] bg-white p-6 transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_35px_-26px_rgba(39,40,34,.45)]"><span className="grid size-10 place-items-center rounded-xl bg-[#f0f0db] text-[#626319]"><Icon className="size-5" /></span><h3 className="mt-9 text-lg font-semibold tracking-[-0.025em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#70716a]">{description}</p><a href="#how-it-works" className="mt-6 inline-flex items-center gap-1 text-sm font-semibold text-[#5c5d17] hover:text-[#292a24]">Explore the workflow <ArrowRight className="size-3.5" /></a></article>)}</div></section>

    <section id="how-it-works" className="border-y border-[#e3e3dc] bg-white px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.78fr_1.22fr] lg:items-center"><div><p className="landing-kicker">FROM APK TO AGENT-READY</p><h2 className="mt-4 text-balance text-3xl font-semibold tracking-[-0.05em] sm:text-5xl">A workflow your whole team can trust.</h2><p className="mt-5 max-w-md text-base leading-7 text-[#6d6e66]">Start with the human decision. Let agents handle the repetitive work inside a session built for review, control, and clarity.</p><a href={workspaceHref} className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#525316] hover:text-[#292a24]">Start with your APK <ArrowRight className="size-4" /></a></div><div className="relative border-l border-[#dddeda] pl-8 sm:pl-12">{[['01', 'Upload your APK', 'Add the app you want to validate. Sulphur checks it and keeps it in your private workspace.'], ['02', 'Prepare an isolated session', 'A clean Android environment starts with the exact policy you choose—network access stays off by default.'], ['03', 'Connect your approved agent', 'Your agent receives a scoped MCP connection, current UI state, and only the actions your policy permits.'], ['04', 'Review every outcome', 'Watch the session, inspect the action log, pause access, or end the environment whenever you need.']].map(([number, title, description], index) => <div key={title} className="relative pb-9 last:pb-0"><span className="absolute -left-[42px] top-0 grid size-5 place-items-center rounded-full border border-[#cfd0a9] bg-[#f8f8f6] text-[8px] font-bold text-[#656618] sm:-left-[54px]">{index + 1}</span><p className="text-[11px] font-bold tracking-[0.14em] text-[#77781d]">{number}</p><h3 className="mt-2 text-lg font-semibold tracking-[-0.02em]">{title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-[#6d6e66]">{description}</p></div>)}</div></div></section>

    <section id="security" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="rounded-3xl bg-[#292a24] px-6 py-10 text-[#f7f7f1] sm:px-10 sm:py-14 lg:px-14"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-[11px] font-semibold tracking-[0.12em] text-[#d9ce22]">SECURITY IS A PRODUCT FEATURE</p><h2 className="mt-4 text-balance text-3xl font-semibold tracking-[-0.05em] sm:text-5xl">Your agent has a job. It doesn’t need the keys to everything.</h2><p className="mt-5 max-w-md text-sm leading-6 text-[#c2c3bc]">Sulphur is designed around policies, isolation, and evidence—not vague assurances. You decide the environment, the connection, and the point at which a person needs to approve.</p><a href="#pricing" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#dedb49] hover:text-white">Explore plans <ArrowRight className="size-4" /></a></div><div className="grid gap-3 sm:grid-cols-2">{securityItems.map(([title, description], index) => <article key={title} className="rounded-xl border border-white/10 bg-white/[0.045] p-5"><span className="grid size-8 place-items-center rounded-lg bg-[#d9ce22] text-[#34351d]">{index === 0 ? <Layers3 className="size-4" /> : index === 1 ? <Globe2 className="size-4" /> : index === 2 ? <Fingerprint className="size-4" /> : <PanelTop className="size-4" />}</span><h3 className="mt-7 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-[#bdbeb7]">{description}</p></article>)}</div></div></div></section>

    <section className="border-y border-[#e3e3dc] bg-white px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-4xl text-center"><p className="landing-kicker">BUILT FOR HUMAN OVERSIGHT</p><blockquote className="mt-6 text-balance text-2xl font-medium leading-[1.25] tracking-[-0.04em] text-[#30312b] sm:text-4xl">“The best agent workflow is not the one that hides the most work. It’s the one that makes every consequential action easy to understand and govern.”</blockquote><div className="mt-8 flex items-center justify-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#eeeece] text-sm font-semibold text-[#66671d]">S</span><div className="text-left"><p className="text-sm font-semibold">The Sulphur approach</p><p className="text-xs text-[#777870]">Human-led, agent-accelerated mobile testing</p></div></div></div></section>

    <section id="pricing" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-2xl text-center"><p className="landing-kicker">START WITH A WORKSPACE</p><h2 className="mt-4 text-balance text-3xl font-semibold tracking-[-0.05em] sm:text-5xl">Ready when your first agent is.</h2><p className="mt-5 text-base leading-7 text-[#6d6e66]">Create a private workspace, upload a test APK, and see your mobile product through an agent’s eyes—with your team still in control.</p></div><div className="mx-auto mt-11 max-w-md rounded-2xl border border-[#dcdcd5] bg-white p-6 shadow-[0_20px_45px_-35px_rgba(39,40,34,.5)]"><div className="flex items-start justify-between"><div><h3 className="text-lg font-semibold">Developer workspace</h3><p className="mt-1 text-sm text-[#70716a]">Everything you need to validate the first agent-ready flow.</p></div><span className="rounded-full bg-[#f0f0db] px-2.5 py-1 text-[10px] font-bold tracking-wide text-[#626319]">EARLY ACCESS</span></div><div className="mt-6 border-y border-[#e9e9e4] py-5"><p className="text-3xl font-semibold tracking-[-0.05em]">Start free</p><p className="mt-1 text-xs text-[#777870]">No card required to create your workspace.</p></div><ul className="mt-5 space-y-3">{['Private workspace and APK library', 'Isolated Android test sessions', 'Scoped MCP connection', 'Session controls and audit history'].map((item) => <li key={item} className="flex items-center gap-2.5 text-sm text-[#55564f]"><CheckCircle2 className="size-4 shrink-0 text-[#638157]" />{item}</li>)}</ul><a href={workspaceHref} className="mt-7 flex h-11 items-center justify-center gap-2 rounded-lg bg-[#292a24] text-sm font-semibold text-white transition hover:bg-[#41423b]">{signedIn ? 'Open dashboard' : 'Create your workspace'} <ArrowRight className="size-4" /></a></div></section>

    <section className="border-t border-[#e3e3dc] bg-white px-5 py-20 sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="landing-kicker">COMMON QUESTIONS</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">Everything should be clear before an agent connects.</h2></div><div className="divide-y divide-[#e5e5df] border-y border-[#e5e5df]">{[['What is Sulphur for?', 'Sulphur gives teams an isolated, observable Android environment where an approved AI agent can inspect and test a customer-authorized APK through a scoped MCP connection.'], ['Can an agent access my production systems?', 'Not by default. Sessions start with egress blocked, and your team controls which network access, policies, and approval steps apply to each session.'], ['What happens if the Android UI changes?', 'Agent actions are bound to fresh screen snapshots. Sulphur resolves the target again immediately before the action and returns updated state instead of acting on stale UI.'], ['Who can see what an agent did?', 'Every action is designed to be recorded with its initiating connection, policy decision, outcome, and the relevant session context for review.']].map(([question, answer]) => <details key={question} className="group py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-semibold text-[#383932]">{question}<span className="grid size-6 shrink-0 place-items-center rounded-full bg-[#f1f1ec] text-[#64655d] transition group-open:rotate-45">+</span></summary><p className="max-w-xl pt-3 text-sm leading-6 text-[#6d6e66]">{answer}</p></details>)}</div></div></section>
    <footer className="border-t border-[#e3e3dc] px-5 py-8 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-5 text-xs text-[#777870] sm:flex-row sm:items-center sm:justify-between"><a href="/" className="flex items-center gap-2 text-sm font-semibold text-[#45463f]"><span className="grid size-6 place-items-center rounded bg-[#292a24] text-[10px] text-[#dedb49]">S</span>Sulphur</a><p>Safe, observable Android environments for agents.</p><div className="flex gap-5"><a className="hover:text-[#292a24]" href="#security">Security</a><a className="hover:text-[#292a24]" href="https://github.com" aria-label="Project repository"><GitBranch className="size-4" /></a></div></div></footer>
  </main>
}
