import { ArrowRight, CheckCircle2, FileArchive, LockKeyhole, Play, ShieldCheck, Terminal, Upload } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Badge, Button, Card, Switch } from './components/ui'
import { DashboardOverview } from './components/dashboard-overview'
import { SiteNav } from './components/site-nav'
import { BenchmarkStats } from './components/benchmark-stats'

const story = [
  { eyebrow: '01 · BRING YOUR APK', title: 'Start from the app your team already has.', description: 'Upload a customer-authorized APK once. It stays in your workspace, ready for a controlled test session.', event: 'APK stored privately', icon: Upload },
  { eyebrow: '02 · PREPARE A SESSION', title: 'Give the app a clean place to run.', description: 'Sulphur prepares a dedicated Android environment with the policy you choose. Network access stays blocked unless you explicitly allow it.', event: 'Isolated environment ready', icon: ShieldCheck },
  { eyebrow: '03 · CONNECT AN AGENT', title: 'Let an approved agent see only what it needs.', description: 'The agent gets a scoped MCP connection and a current screen model. Every action remains tied to the session and its policy.', event: 'MCP connection scoped', icon: Terminal },
  { eyebrow: '04 · REVIEW THE WORK', title: 'Keep the final decision with your team.', description: 'Follow the session, inspect the outcome, and pause or end the environment whenever you need.', event: 'Action logged and visible', icon: CheckCircle2 },
]

function FlowPreview({ active }: { active: number }) {
  const current = story[active]
  return <Card className="product-flow-panel">
    <div className="session-screen-bar"><div><strong>{active === 0 ? 'Apps' : active === 1 ? 'Preparing session' : active === 2 ? 'Connect an agent' : 'Android session'}</strong><span>{current.event}</span></div><Badge tone={active < 2 ? 'neutral' : 'safe'}>{active < 2 ? 'Preparing' : 'Running'}</Badge></div>
    <div className="product-flow-canvas" key={active}>
      {active === 0 && <div className="product-scene-card"><p className="eyebrow">ADD AN ANDROID APP</p><div className="apk-dropzone product-upload-zone"><Upload size={21} /><strong>Drop an APK here</strong><span>or click to browse your files</span></div><div className="product-scene-row"><span className="apk-icon"><FileArchive size={16} /></span><div><strong>storefront-staging.apk</strong><small>12.4 MB · private</small></div><CheckCircle2 className="ml-auto size-4 text-[#5d8c55]" /></div><Button>Save app</Button></div>}
      {active === 1 && <div className="product-scene-card product-preparing"><div className="preparation-visual"><div className="phone-outline"><div className="phone-pulse" /></div></div><p className="eyebrow">PREPARING YOUR SESSION</p><h3>Starting isolated environment</h3><p>Sulphur is preparing a private Android environment for your app.</p><div className="product-progress"><span className="done">✓ Validating APK</span><span className="done">✓ Applying session policy</span><span className="current">● Starting Android emulator</span></div></div>}
      {active === 2 && <div className="product-scene-card"><p className="eyebrow">CONNECT AN AGENT</p><h3>Set up MCP</h3><p>Only this running session’s screen state and approved actions are available.</p><div className="connector-recommended"><button className="connector-choice active">Codex</button><button className="connector-choice">Claude Code</button><button className="connector-choice">Gemini CLI</button></div><div className="mcp-setup"><code>codex mcp add sulphur --session ses_8f29</code><span className="product-scoped"><LockKeyhole size={13} /> Session-scoped access</span></div></div>}
      {active === 3 && <div className="product-scene-session"><div className="product-device"><div className="product-device-notch" /><div className="product-device-content"><span className="text-[7px] font-bold text-[#72736c]">STORE FRONT</span><div className="mt-5 h-2.5 w-16 rounded-full bg-[#d9ce22]" /><div className="mt-3 h-1.5 w-20 rounded-full bg-[#e5e5de]" /><div className="mt-5 rounded-lg bg-[#efefe9] p-2"><div className="h-1.5 w-9 rounded-full bg-[#474841]" /><div className="mt-2 h-1 w-full rounded-full bg-[#d5d5ce]" /><div className="mt-1 h-1 w-4/5 rounded-full bg-[#d5d5ce]" /></div><div className="mt-3 rounded-md bg-[#292a24] py-1.5 text-center text-[6px] font-bold text-white">CONTINUE</div></div></div><div className="product-live-audit"><p className="eyebrow">ACTIVITY</p><div><CheckCircle2 className="size-4 text-[#5d8c55]" /><span><strong>Agent read screen state</strong><small>Snapshot 8f29 · allowed</small></span></div><div><CheckCircle2 className="size-4 text-[#5d8c55]" /><span><strong>Navigation completed</strong><small>Fresh state recorded</small></span></div></div></div>}
    </div>
    <div className="session-footer"><span>Step {active + 1} of {story.length}</span><Button variant="outline">{active === 3 ? 'Review activity' : 'Continue'}</Button></div>
  </Card>
}

function SessionFeature() {
  const [egress, setEgress] = useState(false)
  return <Card className="product-feature-session">
    <div className="session-screen-bar"><div><strong>Session defaults</strong><span>Applied before a test environment starts</span></div><Badge tone="safe">Private</Badge></div>
    <div className="product-feature-body"><div><p className="eyebrow">NETWORK POLICY</p><h3>Keep egress blocked by default.</h3><p>Start from a safe baseline, then make an explicit choice when a test requires access to your services.</p></div><div className="product-policy-control"><div><div><strong>Allow network access</strong><span>For the next Android session</span></div><Switch checked={egress} onCheckedChange={setEgress} label="Allow network access for the next session" /></div><p className="product-policy-note"><LockKeyhole size={14} />{egress ? 'Network access will be requested when the session starts.' : 'Outbound traffic remains blocked.'}</p></div></div>
  </Card>
}

export function ProductPage({ signedIn = false }: { signedIn?: boolean }) {
  const [active, setActive] = useState(0)
  const workspaceHref = signedIn ? '/dashboard' : '/auth/signup'
  useEffect(() => {
    const elements = Array.from(document.querySelectorAll<HTMLElement>('[data-story-step]'))
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) setActive(Number((entry.target as HTMLElement).dataset.storyStep)) }), { rootMargin: '-35% 0px -45% 0px', threshold: 0 })
    elements.forEach((element) => observer.observe(element))
    return () => observer.disconnect()
  }, [])
  return <main className="min-h-screen bg-[#f8f8f6] text-[#292a24] selection:bg-[#d9ce22]">
    <SiteNav signedIn={signedIn} active="product" />
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="max-w-3xl"><p className="landing-kicker">THE SULPHUR PRODUCT</p><h1 className="mt-5 text-balance text-4xl font-semibold leading-[.98] tracking-[-.06em] sm:text-6xl lg:text-7xl">A clear path from APK to <span className="text-[#72731d]">agent-ready.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#686961]">Sulphur makes Android automation useful to agents without asking your team to give up visibility, ownership, or control.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#story" className="inline-flex h-12 items-center gap-2 rounded-lg bg-[#292a24] px-5 text-sm font-semibold text-white hover:bg-[#41423b]"><Play className="size-3.5 fill-current" /> Explore the workflow</a><a href={workspaceHref} className="inline-flex h-12 items-center gap-2 rounded-lg border border-[#d9dad2] bg-white px-5 text-sm font-semibold text-[#3f403a] hover:bg-[#f1f1eb]">Create a workspace <ArrowRight className="size-4" /></a></div></div><div className="mt-16 grid gap-4 sm:grid-cols-3"><Card className="product-stat"><strong>Isolated</strong><span>Android environments per session</span></Card><Card className="product-stat"><strong>Scoped</strong><span>MCP access tied to session policy</span></Card><Card className="product-stat"><strong>Visible</strong><span>Human review for consequential work</span></Card></div></section>
    <section id="story" className="border-y border-[#e2e2db] bg-white px-5 py-20 sm:px-8 sm:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="landing-kicker">THE PRODUCT, IN MOTION</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.05em] sm:text-5xl">One careful step after another.</h2><p className="mt-5 text-base leading-7 text-[#686961]">Scroll through a real-world workflow. The session panel follows the story so you can see what changes at every decision point.</p></div><div className="mt-14 grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-20 pb-8 lg:space-y-32">{story.map((step, index) => <article key={step.title} data-story-step={index} className={`product-story-copy ${active === index ? 'is-active' : ''}`}><p>{step.eyebrow}</p><h3>{step.title}</h3><span>{step.description}</span></article>)}</div><div className="lg:sticky lg:top-10 lg:h-fit"><FlowPreview active={active} /></div></div></div></section>
    <section className="border-b border-[#e2e2db] bg-[#efefe9] px-5 py-20 sm:px-8"><div className="mx-auto max-w-7xl"><BenchmarkStats /></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="landing-kicker">THE REAL PRODUCT EXPERIENCE</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.05em] sm:text-5xl">Not a marketing mockup.</h2><p className="mt-5 text-base leading-7 text-[#686961]">These are the same product components used in the workspace, rendered here so you can understand the experience before creating an account.</p></div><a href={workspaceHref} className="inline-flex items-center gap-2 text-sm font-semibold text-[#5d5e18] hover:text-[#292a24]">Open a workspace <ArrowRight className="size-4" /></a></div><div className="product-dashboard-frame mt-12"><DashboardOverview appsCount={1} /></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><SessionFeature /><Card className="product-audit-card"><p className="eyebrow">ACTIVITY</p><h3>Every event has context.</h3><p>Follow what an approved agent asked to do, what your session allowed, and what changed after the action.</p><div className="product-audit-log"><div><span className="bg-[#eff0d8] text-[#66671d]">1</span><p><strong>Agent requested screen state</strong><small>Snapshot 8f29 returned</small></p></div><div><span className="bg-[#eff5ec] text-[#4c7a45]">2</span><p><strong>Policy allowed navigation</strong><small>Semantic target resolved</small></p></div><div><span className="bg-[#eeeeea] text-[#666760]">3</span><p><strong>Fresh screen state recorded</strong><small>Audit event appended</small></p></div></div></Card></div></section>
    <section className="border-t border-[#e3e3dc] bg-[#292a24] px-5 py-20 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-end"><div className="max-w-2xl"><p className="text-[11px] font-bold tracking-[.13em] text-[#d9ce22]">YOUR WORKSPACE, YOUR RULES</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.05em] sm:text-5xl">Bring your first Android agent workflow under control.</h2><p className="mt-5 text-sm leading-6 text-[#c1c2ba]">Create a workspace, add an APK, and decide exactly how an agent can help.</p></div><a href={workspaceHref} className="inline-flex h-12 shrink-0 items-center gap-2 rounded-lg bg-[#d9ce22] px-5 text-sm font-semibold text-[#34351a] hover:bg-[#e7df4b]">{signedIn ? 'Open dashboard' : 'Create your workspace'} <ArrowRight className="size-4" /></a></div></section>
  </main>
}
