import { ArrowRight, CheckCircle2, FileText, Mail, ShieldCheck, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { useParams } from 'react-router-dom'
import { Card } from './components/ui'
import { SiteNav } from './components/site-nav'
import { startCheckout } from './storage'

const legalPages: Record<string, { title: string; summary: string; sections: string[] }> = {
  terms: { title: 'Terms of service', summary: 'The rules for using Sulphur and creating a workspace.', sections: ['Your workspace and account', 'Permitted use of the service', 'Availability, changes, and support', 'Fees and suspension'] },
  privacy: { title: 'Privacy policy', summary: 'How Sulphur handles account details, product data, and support communications.', sections: ['Information we collect', 'How we use information', 'Retention and deletion', 'Your privacy choices'] },
  cookies: { title: 'Cookie policy', summary: 'How essential cookies and local storage help Sulphur operate safely.', sections: ['Essential service cookies', 'Authentication and preferences', 'Analytics choices', 'How to control cookies'] },
  dpa: { title: 'Data processing addendum', summary: 'The processing terms for customers that use Sulphur as a business service.', sections: ['Scope and roles', 'Confidentiality and safeguards', 'Subprocessors', 'International transfers'] },
  'acceptable-use': { title: 'Acceptable use policy', summary: 'The boundaries that keep Android test environments safe for everyone.', sections: ['Authorized APKs only', 'No production-sensitive automation', 'No environment escape attempts', 'Enforcement'] },
  subprocessors: { title: 'Subprocessors', summary: 'A current list of service categories that may process limited customer data.', sections: ['Infrastructure providers', 'Authentication services', 'Support operations', 'Change notifications'] },
  security: { title: 'Security overview', summary: 'The product controls Sulphur uses to protect isolated Android testing.', sections: ['Session isolation', 'Network and identity controls', 'Logging and access review', 'Responsible disclosure'] },
}

export function ResourcesPage({ signedIn }: { signedIn?: boolean }) { return <main className="min-h-screen bg-[#f8f8f6] text-[#292a24]"><SiteNav signedIn={signedIn} active="resources" /><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28"><p className="landing-kicker">RESOURCES</p><h1 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-.06em] sm:text-6xl">The thinking behind safer mobile agents.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#686961]">Product notes, release updates, and practical guidance for teams bringing agent workflows to Android.</p><div className="mt-14 grid gap-4 md:grid-cols-2"><Card className="resource-card" id="blog"><Sparkles className="size-5 text-[#70711d]" /><p className="eyebrow">BLOG</p><h2>Agent-ready mobile testing</h2><span>How teams can make automation faster without losing the human context behind the work.</span><a href="/product">Read the product story <ArrowRight className="size-4" /></a></Card><Card className="resource-card" id="changelog"><FileText className="size-5 text-[#70711d]" /><p className="eyebrow">CHANGELOG</p><h2>What is changing in Sulphur</h2><span>Track product improvements, new controls, and updates to the agent connection experience.</span><a href="/docs">View documentation <ArrowRight className="size-4" /></a></Card><Card className="resource-card" id="about"><ShieldCheck className="size-5 text-[#70711d]" /><p className="eyebrow">ABOUT</p><h2>Built for human-led automation</h2><span>Sulphur gives engineers an accountable Android surface for the agents they choose to approve.</span><a href="/product">Explore the product <ArrowRight className="size-4" /></a></Card><Card className="resource-card" id="contact"><Mail className="size-5 text-[#70711d]" /><p className="eyebrow">CONTACT</p><h2>Talk with the team</h2><span>Questions about product fit, security, or your planned test workflow?</span><a href="mailto:hello@sulphur.dev">hello@sulphur.dev <ArrowRight className="size-4" /></a></Card></div></section></main> }

const blogPosts = [
  ['SEO for developer tools: make technical value easy to find', 'A practical approach to search-friendly developer-tool content: clear intent, precise page titles, and documentation that answers real implementation questions.'],
  ['How to write product pages that developers actually trust', 'Developer audiences need scope, evidence, and clear tradeoffs—not inflated claims. Here is how to structure a credible technical product page.'],
  ['Mobile testing SEO: the topics teams search before choosing a platform', 'The questions that shape mobile testing research, from emulator security to agent-assisted QA and observable test sessions.'],
]

export function ResourceDetailPage({ signedIn }: { signedIn?: boolean }) { const { resource = 'blog' } = useParams(); const title = resource === 'blog' ? 'Sulphur blog' : resource === 'faq' ? 'Frequently asked questions' : resource === 'changelog' ? 'Changelog' : resource === 'about' ? 'About Sulphur' : 'Contact Sulphur'; return <main className="min-h-screen bg-[#f8f8f6] text-[#292a24]"><SiteNav signedIn={signedIn} active="resources" /><section className="mx-auto max-w-5xl px-5 py-20 sm:px-8 sm:py-28"><a href="/resources" className="text-sm font-semibold text-[#606117]">← Resources</a><p className="landing-kicker mt-9">RESOURCES</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.06em] sm:text-6xl">{title}</h1>{resource === 'blog' ? <div className="mt-12 grid gap-4">{blogPosts.map(([heading, description], index) => <Card key={heading} className="blog-card"><p className="eyebrow">SEARCH & PRODUCT MARKETING · {index + 1}</p><h2>{heading}</h2><p>{description}</p><a href={`/resources/blog#post-${index + 1}`}>Read article <ArrowRight className="size-4" /></a></Card>)}</div> : resource === 'faq' ? <div className="faq-list">{[['What is Sulphur?', 'Sulphur prepares isolated Android environments so approved AI agents can inspect and test authorized APKs through a controlled MCP connection.'], ['Can an agent use my production credentials?', 'No. Sulphur is designed for authorized development and staging workflows. Policies can require approval before consequential actions.'], ['Does every app work identically?', 'No. Accessible Android UI is the strongest path. Custom rendered interfaces may require a constrained visual fallback with clear confidence and policy gates.'], ['Who can review activity?', 'Workspace members can inspect session context, policy outcomes, and the audit trail for actions that occur in their approved sessions.']].map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div> : <Card className="resource-detail-card"><h2>{resource === 'changelog' ? 'Latest updates' : resource === 'about' ? 'A safer surface for mobile agents' : 'Get in touch'}</h2><p>{resource === 'changelog' ? 'The first public release brings private workspaces, APK uploads, controlled Android sessions, session-level MCP guidance, and traceable agent activity.' : resource === 'about' ? 'Sulphur is building an accountable Android testing surface where people set the boundaries and agents accelerate the repetitive work.' : 'For product, security, or partnership questions, email hello@sulphur.dev.'}</p>{resource === 'contact' && <a href="mailto:hello@sulphur.dev">hello@sulphur.dev</a>}</Card>}</section></main> }

const plans = [
  { id: 'free', name: 'Free', description: 'A private workspace for evaluating Sulphur before you upgrade.', monthly: 0, sessions: '5-minute sessions', tools: '1,000 MCP tool calls / day', credits: 'No included credits', features: ['1 active session', 'Private APK workspace', '30-day activity history'] },
  { id: 'team', name: 'Team', description: 'For teams running dependable, shared mobile automation.', monthly: 79, sessions: '50 session hours / month', tools: '15,000 MCP tool calls / day', credits: '600 included credits', features: ['3 active sessions', 'Shared workspace controls', '90-day activity history'] },
  { id: 'scale', name: 'Scale', description: 'For high-volume work with governance and priority support.', monthly: 249, sessions: '250 session hours / month', tools: '100,000 MCP tool calls / day', credits: '3,000 included credits', features: ['10 active sessions', 'Advanced workspace controls', 'Unlimited activity history'] },
] as const

export function PricingPage({ signedIn }: { signedIn?: boolean }) {
  const [annual, setAnnual] = useState(true)
  const [checkoutError, setCheckoutError] = useState('')
  const [checkoutPlan, setCheckoutPlan] = useState('')
  const href = signedIn ? '/settings/billing' : '/auth/signup'
  const checkout = async (planId: typeof plans[number]['id']) => { if (!signedIn || planId === 'free') return; setCheckoutError(''); setCheckoutPlan(planId); try { window.location.assign((await startCheckout(planId, annual ? 'yearly' : 'monthly')).url) } catch (reason) { setCheckoutError(reason instanceof Error ? reason.message : 'Checkout could not be started.'); setCheckoutPlan('') } }
  return <main className="min-h-screen bg-[#f8f8f6] text-[#292a24]"><SiteNav signedIn={signedIn} active="pricing" /><section className="mx-auto max-w-7xl px-5 py-20 text-center sm:px-8 sm:py-28"><p className="landing-kicker">PRICING</p><h1 className="mt-5 text-4xl font-semibold tracking-[-.06em] sm:text-6xl">More room for every agent run.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[#686961]">Every workspace starts on Free. Add a card in secure checkout to begin a 14-day paid-plan trial.</p><div className="pricing-switch" role="group" aria-label="Billing cadence"><button className={!annual ? 'active' : ''} onClick={() => setAnnual(false)}>Monthly</button><button className={annual ? 'active' : ''} onClick={() => setAnnual(true)}>Yearly <span>Save 20%</span></button></div><div className="mx-auto mt-14 grid max-w-6xl gap-4 text-left md:grid-cols-3">{plans.map((plan, index) => { const free = plan.id === 'free'; const monthly = free ? 0 : annual ? Math.round(plan.monthly * .8) : plan.monthly; return <Card key={plan.id} className={`pricing-card ${index === 1 ? 'featured' : ''}`}>{index === 1 && <span className="pricing-badge">MOST POPULAR</span>}<h2>{plan.name}</h2><p>{plan.description}</p><strong>${monthly}<small>/month</small></strong>{annual && !free && <em className="pricing-annual-note">Billed ${monthly * 12}/year · 20% off</em>}{free ? <a href={href}>{signedIn ? 'Manage free plan' : 'Create free workspace'} <ArrowRight className="size-4" /></a> : signedIn ? <button className="pricing-checkout" disabled={checkoutPlan === plan.id} onClick={() => checkout(plan.id)}>{checkoutPlan === plan.id ? 'Opening secure checkout…' : 'Start 14-day trial'} <ArrowRight className="size-4" /></button> : <a href={href}>Create free workspace <ArrowRight className="size-4" /></a>}<ul><li><CheckCircle2 className="size-4" />{plan.sessions}</li><li><CheckCircle2 className="size-4" />{plan.tools}</li><li><CheckCircle2 className="size-4" />{plan.credits}</li>{plan.features.map((feature) => <li key={feature}><CheckCircle2 className="size-4" />{feature}</li>)}</ul></Card> })}</div>{checkoutError && <p className="form-error mx-auto mt-5 max-w-xl" role="alert">{checkoutError}</p>}<p className="mx-auto mt-10 max-w-xl text-xs leading-5 text-[#777870]">Stripe securely collects your card for paid-plan trials. Cancel before renewal to avoid a charge.</p></section></main>
}

export function LegalPage({ signedIn }: { signedIn?: boolean }) { const { page = 'terms' } = useParams(); const legal = legalPages[page] ?? legalPages.terms; return <main className="min-h-screen bg-[#f8f8f6] text-[#292a24]"><SiteNav signedIn={signedIn} /><section className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[210px_1fr] lg:py-24"><aside className="legal-aside"><p className="landing-kicker">LEGAL</p>{Object.entries(legalPages).map(([slug, item]) => <a className={slug === page ? 'active' : ''} href={`/legal/${slug}`} key={slug}>{item.title}</a>)}</aside><article className="legal-content"><p className="landing-kicker">SULPHUR LEGAL</p><h1>{legal.title}</h1><p className="legal-lede">{legal.summary}</p><p className="legal-updated">Last updated: September 20, 2026</p>{legal.sections.map((section, index) => <section key={section}><h2>{index + 1}. {section}</h2><p>This page describes the principles and operational boundaries that apply to this part of the Sulphur service. It is published as a clear product-policy reference and will be replaced by finalized legal terms before commercial availability.</p></section>)}</article></section></main> }
